version: '3'

services:
  consent:
    image: consent_bb_mock_app
    expose:
      - 8000
    networks:
      - web
    build:
      context: ../../
      dockerfile: examples/mock/Dockerfile_app

  caddy:
    image: consent_bb_mock_http
    ports:
      - '8080:80'
      - '8888:443'
      - '2019'
    environment:
      - SITE_ADDRESS=localhost
    volumes:
      - caddy:/data
    networks:
      - web
    build:
      context: ../../
      dockerfile: examples/mock/Dockerfile_caddy
    volumes:
      - ./caddy:/etc/caddy
      - ./static-responses:/static-reponses

volumes:
  caddy:

networks:
  web:
    driver: bridge
